package com.liferay.pushnotifications.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.liferay.pushnotifications.model.ApplicationPreferences;
import com.liferay.pushnotifications.service.ApplicationPreferencesLocalServiceUtil;

/**
 * The extended model base implementation for the ApplicationPreferences service. Represents a row in the &quot;ApplicationPreferences&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ApplicationPreferencesImpl}.
 * </p>
 *
 * @author Bruno Farache
 * @see ApplicationPreferencesImpl
 * @see com.liferay.pushnotifications.model.ApplicationPreferences
 * @generated
 */
public abstract class ApplicationPreferencesBaseImpl
    extends ApplicationPreferencesModelImpl implements ApplicationPreferences {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a application preferences model instance should use the {@link ApplicationPreferences} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            ApplicationPreferencesLocalServiceUtil.addApplicationPreferences(this);
        } else {
            ApplicationPreferencesLocalServiceUtil.updateApplicationPreferences(this);
        }
    }
}
