package com.liferay.pushnotifications.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.liferay.pushnotifications.model.Application;
import com.liferay.pushnotifications.service.ApplicationLocalServiceUtil;

/**
 * The extended model base implementation for the Application service. Represents a row in the &quot;Application&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ApplicationImpl}.
 * </p>
 *
 * @author Bruno Farache
 * @see ApplicationImpl
 * @see com.liferay.pushnotifications.model.Application
 * @generated
 */
public abstract class ApplicationBaseImpl extends ApplicationModelImpl
    implements Application {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a application model instance should use the {@link Application} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            ApplicationLocalServiceUtil.addApplication(this);
        } else {
            ApplicationLocalServiceUtil.updateApplication(this);
        }
    }
}
