package com.liferay.pushnotifications.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.liferay.pushnotifications.model.AppVersion;
import com.liferay.pushnotifications.service.AppVersionLocalServiceUtil;

/**
 * The extended model base implementation for the AppVersion service. Represents a row in the &quot;AppVersion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AppVersionImpl}.
 * </p>
 *
 * @author Bruno Farache
 * @see AppVersionImpl
 * @see com.liferay.pushnotifications.model.AppVersion
 * @generated
 */
public abstract class AppVersionBaseImpl extends AppVersionModelImpl
    implements AppVersion {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a app version model instance should use the {@link AppVersion} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            AppVersionLocalServiceUtil.addAppVersion(this);
        } else {
            AppVersionLocalServiceUtil.updateAppVersion(this);
        }
    }
}
