package com.liferay.pushnotifications.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.liferay.pushnotifications.model.PushNotificationsDevice;
import com.liferay.pushnotifications.service.PushNotificationsDeviceLocalServiceUtil;

/**
 * The extended model base implementation for the PushNotificationsDevice service. Represents a row in the &quot;PushNotificationsDevice&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PushNotificationsDeviceImpl}.
 * </p>
 *
 * @author Bruno Farache
 * @see PushNotificationsDeviceImpl
 * @see com.liferay.pushnotifications.model.PushNotificationsDevice
 * @generated
 */
public abstract class PushNotificationsDeviceBaseImpl
    extends PushNotificationsDeviceModelImpl implements PushNotificationsDevice {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a push notifications device model instance should use the {@link PushNotificationsDevice} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            PushNotificationsDeviceLocalServiceUtil.addPushNotificationsDevice(this);
        } else {
            PushNotificationsDeviceLocalServiceUtil.updatePushNotificationsDevice(this);
        }
    }
}
