package com.liferay.pushnotifications.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Application service. Represents a row in the &quot;Application&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.pushnotifications.model.impl.ApplicationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.pushnotifications.model.impl.ApplicationImpl}.
 * </p>
 *
 * @author Bruno Farache
 * @see Application
 * @see com.liferay.pushnotifications.model.impl.ApplicationImpl
 * @see com.liferay.pushnotifications.model.impl.ApplicationModelImpl
 * @generated
 */
public interface ApplicationModel extends BaseModel<Application> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a application model instance should use the {@link Application} interface instead.
     */

    /**
     * Returns the primary key of this application.
     *
     * @return the primary key of this application
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this application.
     *
     * @param primaryKey the primary key of this application
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the application ID of this application.
     *
     * @return the application ID of this application
     */
    public long getApplicationId();

    /**
     * Sets the application ID of this application.
     *
     * @param applicationId the application ID of this application
     */
    public void setApplicationId(long applicationId);

    /**
     * Returns the application name of this application.
     *
     * @return the application name of this application
     */
    @AutoEscape
    public String getApplicationName();

    /**
     * Sets the application name of this application.
     *
     * @param applicationName the application name of this application
     */
    public void setApplicationName(String applicationName);

    /**
     * Returns the created date of this application.
     *
     * @return the created date of this application
     */
    public Date getCreatedDate();

    /**
     * Sets the created date of this application.
     *
     * @param createdDate the created date of this application
     */
    public void setCreatedDate(Date createdDate);

    /**
     * Returns the modificated date of this application.
     *
     * @return the modificated date of this application
     */
    public Date getModificatedDate();

    /**
     * Sets the modificated date of this application.
     *
     * @param modificatedDate the modificated date of this application
     */
    public void setModificatedDate(Date modificatedDate);

    /**
     * Returns the user ID of this application.
     *
     * @return the user ID of this application
     */
    public long getUserId();

    /**
     * Sets the user ID of this application.
     *
     * @param userId the user ID of this application
     */
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this application.
     *
     * @return the user uuid of this application
     * @throws SystemException if a system exception occurred
     */
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this application.
     *
     * @param userUuid the user uuid of this application
     */
    public void setUserUuid(String userUuid);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Application application);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Application> toCacheModel();

    @Override
    public Application toEscapedModel();

    @Override
    public Application toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
