package com.liferay.pushnotifications.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PushNotificationsDevice service. Represents a row in the &quot;PushNotificationsDevice&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.pushnotifications.model.impl.PushNotificationsDeviceModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.pushnotifications.model.impl.PushNotificationsDeviceImpl}.
 * </p>
 *
 * @author Bruno Farache
 * @see PushNotificationsDevice
 * @see com.liferay.pushnotifications.model.impl.PushNotificationsDeviceImpl
 * @see com.liferay.pushnotifications.model.impl.PushNotificationsDeviceModelImpl
 * @generated
 */
public interface PushNotificationsDeviceModel extends BaseModel<PushNotificationsDevice> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a push notifications device model instance should use the {@link PushNotificationsDevice} interface instead.
     */

    /**
     * Returns the primary key of this push notifications device.
     *
     * @return the primary key of this push notifications device
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this push notifications device.
     *
     * @param primaryKey the primary key of this push notifications device
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the push notifications device ID of this push notifications device.
     *
     * @return the push notifications device ID of this push notifications device
     */
    public long getPushNotificationsDeviceId();

    /**
     * Sets the push notifications device ID of this push notifications device.
     *
     * @param pushNotificationsDeviceId the push notifications device ID of this push notifications device
     */
    public void setPushNotificationsDeviceId(long pushNotificationsDeviceId);

    /**
     * Returns the user ID of this push notifications device.
     *
     * @return the user ID of this push notifications device
     */
    public long getUserId();

    /**
     * Sets the user ID of this push notifications device.
     *
     * @param userId the user ID of this push notifications device
     */
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this push notifications device.
     *
     * @return the user uuid of this push notifications device
     * @throws SystemException if a system exception occurred
     */
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this push notifications device.
     *
     * @param userUuid the user uuid of this push notifications device
     */
    public void setUserUuid(String userUuid);

    /**
     * Returns the create date of this push notifications device.
     *
     * @return the create date of this push notifications device
     */
    public Date getCreateDate();

    /**
     * Sets the create date of this push notifications device.
     *
     * @param createDate the create date of this push notifications device
     */
    public void setCreateDate(Date createDate);

    /**
     * Returns the platform of this push notifications device.
     *
     * @return the platform of this push notifications device
     */
    @AutoEscape
    public String getPlatform();

    /**
     * Sets the platform of this push notifications device.
     *
     * @param platform the platform of this push notifications device
     */
    public void setPlatform(String platform);

    /**
     * Returns the token of this push notifications device.
     *
     * @return the token of this push notifications device
     */
    @AutoEscape
    public String getToken();

    /**
     * Sets the token of this push notifications device.
     *
     * @param token the token of this push notifications device
     */
    public void setToken(String token);

    /**
     * Returns the model of this push notifications device.
     *
     * @return the model of this push notifications device
     */
    @AutoEscape
    public String getModel();

    /**
     * Sets the model of this push notifications device.
     *
     * @param model the model of this push notifications device
     */
    public void setModel(String model);

    /**
     * Returns the o s version of this push notifications device.
     *
     * @return the o s version of this push notifications device
     */
    @AutoEscape
    public String getOSVersion();

    /**
     * Sets the o s version of this push notifications device.
     *
     * @param OSVersion the o s version of this push notifications device
     */
    public void setOSVersion(String OSVersion);

    /**
     * Returns the app ID of this push notifications device.
     *
     * @return the app ID of this push notifications device
     */
    public long getAppId();

    /**
     * Sets the app ID of this push notifications device.
     *
     * @param appId the app ID of this push notifications device
     */
    public void setAppId(long appId);

    /**
     * Returns the app version of this push notifications device.
     *
     * @return the app version of this push notifications device
     */
    @AutoEscape
    public String getAppVersion();

    /**
     * Sets the app version of this push notifications device.
     *
     * @param appVersion the app version of this push notifications device
     */
    public void setAppVersion(String appVersion);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(PushNotificationsDevice pushNotificationsDevice);

    @Override
    public int hashCode();

    @Override
    public CacheModel<PushNotificationsDevice> toCacheModel();

    @Override
    public PushNotificationsDevice toEscapedModel();

    @Override
    public PushNotificationsDevice toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
